name: ZEnchantmentCore
main: com.hoodiecoder.enchantmentcore.EnchantmentCore
version: v1.3.0-beta
api-version: 1.16
depend: []
commands:
    zenchantment:
      description: Main ZEnchantmentCore command.
      usage: /zenchantment [args]
    ze:
      description: Main ZEnchantmentCore command.
      usage: /ze [args]
permissions:
  zenchantmentcore.help:
    description: Allows player to use /ze help.
    default: true
  zenchantmentcore.util:
    description: Allows player to use /ze utility commands.
    default: op