# # # # # # # # # #
# GENERAL OPTIONS #
# # # # # # # # # #

# Disables any enchantments in the list, ex. ['zenchantments-basic:life_steal', 'my_plugin:my_enchant']
disabled-enchantments: []

# # # # # # # # # # #
# GENERATOR OPTIONS #
# # # # # # # # # # #

# Enables the custom enchantment generator. This should be on if you want your enchantments to appear in survival Minecraft.
enable-custom-generator: true

# Change the enchantment generator options
# The following options only apply if enable-custom-generator is set to true
enchantment-generator:
  # Allows enchanting books with multiple enchantments in the enchantment table
  allow-stacked-books: false
  # Allows treasure enchantments to show up in the enchantment table
  allow-treasure-enchants: false
  # Changes the probability of getting an additional enchantment (multiple enchantments) when enchanting
  enchantment-amount-multiplier: 1.0
  # Enchants axes as if they were also swords
  treat-axes-as-weapons: false
  # Allows the player to apply illegal enchantments using anvils in survival mode
  allow-survival-illegal-enchants: false
  # Allows the player to apply illegal enchantments using anvils in creative mode
  allow-creative-illegal-enchants: true