# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: 16
    - name: Unshallow
      run: git fetch --unshallow --quiet
    - name: Build with Maven
      run: mvn -B package
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: "ZEnchantmentCore"
        path: "./target/ZEnchantmentCore.jar"
  javadocs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: 16
    - name: Unshallow
      run: git fetch --unshallow --quiet
    - name: Generate Javadocs
      run: mvn install javadoc:aggregate-no-fork
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site/apidocs
