name: Build & Release

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
      - name: Unshallow
        run: git fetch --unshallow --quiet
      - name: Build with Maven
        run: mvn -B install javadoc:aggregate-no-fork
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "ZEnchantmentCore"
          path: "./target/ZEnchantmentCore.jar"
      - name: Upload artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "./target/ZEnchantmentCore.jar"
          tag: ${{ github.ref }}
      - name: Deploy Javadocs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
      - name: Publish Package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
